[workspace]
resolver = "2"
members = [
    "neetcode/sliding-window/longest-repeating-character-replacement",
    "merge-strings-alternately",
    "gcd-of-strings",
    "close-strings",
    "number-of-provinces"
]
