[workspace]
resolver = "2"
members = [
    "neetcode/sliding-window/longest-repeating-character-replacement",
    "merge-strings-alternately",
    "close-strings",
    "number-of-provinces",
    "maximum-average-subarray",
    "maximum-number-of-vowels",
]
