[package]
name = "min-in-rotated-sorted-array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "min-in-rotated-sorted-array"
path = "min-in-rotated-sorted-array.rs"
