[package]
name = "gcd-of-strings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "gcd-of-strings"
path = "gcd-of-strings.rs"
