[package]
name = "remove-nth-node-from-end-of-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "remove-nth-node-from-end-of-list"
path = "remove-nth-node-from-end-of-list.rs"
