[package]
name = "number-of-provinces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "number-of-provinces"
path = "number-of-provinces.rs"
