[package]
name = "diameter-of-binary-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "diameter-of-binary-tree"
path = "diameter-of-binary-tree.rs"
